### ISSUE TITLE
role "${dbuser}" does not exist

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#14]
Every time the server started it throws the following error:
FATAL: role "${dbuser}" does not exist
at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:684) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:199) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
...
the stack trace is very long
org.hibernate.tool.hbm2ddl.SchemaUpdate  : HHH000319: Could not get database metadata

**Comment by imarban** [comment]
Are you overriding the database properties in Maven run statement?

**Comment by wdonet** [comment]
you'r right, I had forgotten that.
We should do mvn spring-boot:run -Ddbuser=myuserinmylocaldbpostgres, locally
ty .. closing this bug
